version: "3.8"

services:
  fpm:
    build:
      context: ./
      dockerfile: ./docker/php-fpm/8.3-local/Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    volumes:
      - ./:/var/www
    ports:
      - "${FPM_PORT}:9001"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    build:
      context: ./docker/nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ./:/var/www:rw
    depends_on:
      - fpm
